# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e519f9a6e9c515fcbe9805587712d7de1fbff6bb04c4e76e070dc8471a2ca931ed94b5df3923bba3724b20682cf64aba43525dde62b7794b05a4afb9c44273ef

test:
  secret_key_base: 61e7de0a1b1758ea98b62de9bad4d6a0ca0cfd5a8ede17c3e682ed644ecef2b76e03b26087ce1bff3d38809f00396f49f7bdf4b0d98eba84f3ecb16e3357778f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
